# Site settings
title: "Hongyang Li, Academic Notes"
email: 
description: "A surfer in the vision ocean."
baseurl: ""
url: "http://hli2020.github.io"
twitter_username: francislee2020
github_username:  hli2020

# Build settings
markdown: redcarpet
permalink: pretty
