# Site settings
title: Andrej Karpathy blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://karpathy.github.io"
twitter_username: karpathy
github_username:  karpathy

# Build settings
markdown: redcarpet
permalink: pretty
